# Generated by Django 5.0.2 on 2024-02-28 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_product_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500)),
                ('avgprice', models.IntegerField(max_length=30)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.product_detail')),
            ],
        ),
    ]
