# Generated by Django 5.0.2 on 2024-02-29 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_brand_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_detail',
            name='avgprice',
            field=models.IntegerField(max_length=10),
        ),
        migrations.CreateModel(
            name='Final_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specify', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=10)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.brand_detail')),
            ],
        ),
    ]
