# Generated by Django 5.0.2 on 2024-02-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_final_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_detail',
            name='price',
            field=models.FloatField(max_length=10),
        ),
    ]
