# Generated by Django 5.0.2 on 2024-02-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_alter_final_detail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_detail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
