# Generated by Django 5.0.2 on 2024-03-01 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_alter_brand_detail_avgprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_detail',
            name='avgprice',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='final_detail',
            name='price',
            field=models.IntegerField(max_length=15),
        ),
        migrations.CreateModel(
            name='Conclude_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_specify', models.CharField(max_length=200)),
                ('pro_brand', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=15)),
                ('image', models.CharField(default='', max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('color', models.CharField(max_length=20)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.brand_detail')),
            ],
        ),
    ]
